GET http://127.0.0.1:5000/receitas/1 HTTP/1.1
content-type: application/json

##########################
POST http://127.0.0.1:5000/receitas HTTP/1.1
content-type: application/json

{
    "titulo": "Brigadeiro de casca de banana",
    "ingredientes": "Cascas de 2 bananas, bem lavadas e picadas; 1 lata de leite condensado; 4 colheres (sopa) de chocolate em pó; 1 colher (sopa) de margarina ou manteiga",
    "preparo": "Bata todos os ingredientes no liquidificador. Leve a mistura ao fogo baixo para ferver, mexendo sempre até começar a soltar do fundo. Desligue e deixe esfriar. Depois, você pode enrolar e passar no granulado ou servir em copinhos.",
    "img": "imgur.com/brigadeiro.jpeg"
}

##########################
PUT http://127.0.0.1:5000/receitas/1 HTTP/1.1
content-type: application/json

{
    "titulo": "Brigadeiro de casca de banana",
    "ingredientes": "Cascas de 2 bananas, bem lavadas e picadas; 1 lata de leite condensado; 4 colheres (sopa) de chocolate em pó; 1 colher (sopa) de margarina ou manteiga",
    "preparo": "Bata todos os ingredientes no liquidificador. Leve a mistura ao fogo baixo para ferver, mexendo sempre até começar a soltar do fundo. Desligue e deixe esfriar. Depois, você pode enrolar e passar no granulado ou servir em copinhos.",
    "img": "imgur.com/brigadeiro_casca_banana.jpeg"
}


##########################
DELETE http://127.0.0.1:5000/receitas/1 HTTP/1.1
content-type: application/json
